name: fat_ads
description: A simple and easy-to-use Flutter package to integrate Ads into your app.
version: 0.2.0
repository: https://github.com/damphat/fat_ads.git

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.3.0
  provider: ^6.0.5
  xml: ^6.1.0
  collection: ^1.16.0
  json5: ^0.8.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
